M48
; DRILL file {KiCad (6.0.10)} date Fri Jun  2 17:32:59 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-02T17:32:59+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.8819Y-1.9685
X4.8819Y-4.5669
X8.3858Y-1.9685
X8.3858Y-4.5669
T0
M30
